# Generated by Django 5.1 on 2024-08-08 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=13)),
                ('age', models.IntegerField()),
                ('enrollmentdate', models.DateField()),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.course')),
            ],
        ),
    ]
